import { Quicksand } from "next/font/google";
import local from "next/font/local";
import "./globals.css";

const quicksand = Quicksand({ subsets: ["latin"] });
const neue_montreal = local({
  src: "../../public/fonts/NeueMontreal-Regular.woff",
  variable: "--font-neue-montreal",
});
const founders_grotesk = local({
  src: "../../public/fonts/FoundersGrotesk-Semibold.woff",
  variable: "--font-founders-grotesk",
});

export const metadata = {
  title: "Yash Bele | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} ${neue_montreal.variable} ${founders_grotesk.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
